### ISSUE TITLE
Export folders with subfolders and links

### ISSUE THREAD

**Issue by astiglic** [igorlogius/export-bookmarks-as-text#1] opened 2023-04-30 17:07 UTC
I've installed the extension.
I can see the icon, but it doesn't do anything when I click on it.
I had similar extension few years back and it's extremely valuable extension.
Using latest firefox 112.0.2

**Comment by igorlogius** [comment] 2023-04-30 19:16
It should start a download ... if you have your browser configured to not show up the download popup, then you might not have noticed it, but if you check your default or last download folder ... there should be a file called `YYYY-MM-DD_hh-mm-ss_bookmarks.txt`


https://user-images.githubusercontent.com/67047467/235372109-ebe05d53-abad-4a88-9c5a-b82bb5d73b27.mp4

Hope this info helps.

**Comment by igorlogius** [comment] 2023-05-01 12:38
@astiglic 

Did my reply help you, or is there still something not working as expected (in regards to the addon) ?

**Comment by astiglic** [comment] 2023-05-07 11:42
Hi,
Sorry for late reply. I've triple check all the procedures, cleaned up the download directory and switch to automatic download without asking for file name, and now I can see the new files being generated, but they seem interrupted, so instead file with date and .txt I got files like this
RQjAfg9r.txt.part
like uncompleted download.
I tried switching the download file name option on and off, switched all the extensions off, except yours, but result stayed the same.
The content of the file seems there, and the file format is UNIX.
I hope that might help with debugging.
Windows 10 Pro, 21H2, 19044.2846, Firefox 112.0.2 (64-bit)

**Comment by igorlogius** [comment] 2023-05-07 13:46
> Sorry for late reply.

no problem, i was already expecting this issue to be resolved so ... but let's reboot it.

>  now I can see the new files being generated, but they seem interrupted, so instead file with date and .txt I got files like this RQjAfg9r.txt.part

That looks strange. I have to be honest, i havent see that before. 

The `*.part` is a partial file. Of the top of my head i dont even know if firefox uses part files ... maybe for large files but not for small stuff ... if you would have ask me ... before, i would have said, that this looks more like some other application is trying to over the download from firefox. (aka. canceling it and failed to finish it then) 

Do you maybe have any other software installed, that could do this?  That would also explain them never being completed, since it is unlikely that the data can be passed on to the other application correctly, since it is not a real url used for downloading here.

**Comment by igorlogius** [comment] 2023-05-07 16:04
If you dont have any software installed, that could be the culpid, then please create a new profile and only installe the addon, and check if the issue also persists in this new empty profile. Please let me know about the results.

**Comment by astiglic** [comment] 2023-05-08 08:28
Yes, in the new profile it works. What is culpid ?


-----Original Message-----

**Comment by astiglic** [comment] 2023-05-08 08:44
Since now I finally see how it should work, it would be great for filename not to start with numbers, or have the option to swap that around. Ideally it should have the name of the folder at the start.
For example if the folder is Music the file name could be:
bookmarks_Music_2023-05-09_10-27-17.txt

**Comment by igorlogius** [comment] 2023-05-08 09:43
> Yes, in the new profile it works. 

That is good to know, then the issue is with your profile settings


> What is culpid ?

Well ... sorry but i dont know, at least i havent encountered that issue before, but if you find out, it would be very kind of you to let me know, so i can add it to the addons troubleshooting descriptions.

**Comment by igorlogius** [comment] 2023-05-08 09:45
> Since now I finally see how it should work, it would be great for filename not to start with numbers, or have the option to swap that around. Ideally it should have the name of the folder at the start. For example if the folder is Music the file name could be: bookmarks_Music_2023-05-09_10-27-17.txt

Please open another feature request issue for this. 
Then i'll see what i can do. Thanks. 

Closing this issue, but if you find the what causes the issue in your profile setting, do not hesitate to add the solution/culip here as a comment. Thanks.

**Closed by igorlogius** 2023-05-08 09:45 UTC
Labels: bug, 🍹 Discussion, 🔍 Needs Investigation, 🛟 Help/Support
